services:
  web:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 8443:8443
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/bbdd
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - db
    restart: on-failure
  db:
    image: mysql:9.2
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=bbdd
    volumes:
      - ./mysql:/var/lib/mysql